permalink: /:year/:month/:day/:title.html
# 当修改文件时重新生成站点
auto: true
pygments: true
title: 码代码的马--Github博客
github_username:  coleflowers
production_url : https://coleflowers.github.io
# baseurl: /coleflowers.github.com
baseurl  : /
#comments :
#  provider : disqus
#  disqus   :
#staticman:
#  branch   : "master"

#short_name : coleflowers
# 基本参数

# 
# atom_path      : /atom.xml
author:
  name: coleflowers
  email: coleflowers@163.com
