permalink: /:year/:month/:day/:title.html
# 当修改文件时重新生成站点
auto: true
pygments: true
# baseurl: /coleflowers.github.com
baseurl  : /
comments :
provider : disqus
branch   : "master"
disqus   :
short_name : coleflowers
# 基本参数
title          : 码代码的马--Github博客
production_url : https://coleflowers.github.io
atom_path      : /atom.xml
author :
  name : coleflowers
  email : coleflowers@163.com
